Removed lambdas from EquivariantLieTransformer
This removes the error:

AttributeError: Can't pickle local object 'EquivariantTransformerBlock.__init__.<locals>.<lambda>'

when trying to save EquivariantLieTransformer models, caused by the inability for the pickle library
to handle lambda functions.